apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gcr.io/roi-dtcuser316/internal-image:v2.0.0
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: roi-dtcuser316
        ports:
        - containerPort: 8082
            
        
